name: Build Go Binary

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23' # adjust to your Go version

      - name: Build static binary
        run: |
          mkdir -p bin
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o bin/app .

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: app-linux-amd64
          path: bin/app
